### ISSUE TITLE
[Suggestion]: get nav_bar state from st.session_state

### ISSUE THREAD

**Issue by saeedshojaee** [TangleSpace/hydralit_components#11]
Thanks for the cool library. I am using streamlit for a multipage app, and I have some buttons that callback to change a page.
I used to use `streamlit.radio()` for that matter, and defined a page class as below. this allowed me to create simple callbacks, and streamlit would update the radio after the rerun.

```
class Page():
    key= "page"

    @classmethod
    def render(cls):
        return st.radio(
                "page",
                options=["page1", "page2"],
                key=cls.key,
            )
       

    @classmethod
    def update(cls, value):
        st.session_state[cls.key] = value
        
    @classmethod
    def value(cls):
        return st.session_state[cls.key]
```
example of callback:
```
def navigate_to_page2():
    Page.update("page2")
    ```    
I was trying to change the to hyralit_component, I used similar approach and defined `HydralitPage` as below.
```
class HydralitPage(Page):
    key= "hydralit_page"

    @classmethod
    def render(cls):
        menu_data = [
           {"label": "page1"},
           {"label": "page2"}
        ]

        over_theme = {"txc_inactive": "#FFFFFF"}
        hc.nav_bar(
            menu_definition=menu_data,
            override_theme=over_theme,
            home_name=None,
            login_name=None,
            hide_streamlit_markers=False,  # will show the st hamburger as well as the navbar now!
            sticky_nav=True,  # at the top or not
            sticky_mode="pinned",  # jumpy or not-jumpy, but sticky or pinned
            key=cls.key,
        )
        return cls.value()
 ```
 Although I am still to use the callbacks and the content changes, the navigation bar does not get updated
![animation](https://user-images.githubusercontent.com/29708838/141986358-2db11caa-4f15-4559-b757-429346da20de.gif)
.

**Comment by TangleSpace** [comment]
Thanks for the feedback, you can save yourself alot of work in creating a multi-page app, the sister library to this package is https://github.com/TangleSpace/hydralit, this takes care of everything related to creating multi-page apps, it already uses the session state to take care of the navigation, it also includes the ability to use app transition loaders, secure access etc. I recommend you look at Hydralit as it this navbar was created for the multi-page library and uses the session state and alot more already. https://github.com/TangleSpace/hydralit
