### ISSUE TITLE
How to have individual page to show different things?

### ISSUE THREAD

**Issue by lchunleo** [TangleSpace/hydralit_components#12]
Thanks for the good work and sharing.

i am checking out the code but somehow, i can't find a way to have different contents stuff to appear in different menu items. Can advise ? thank you

**Comment by TangleSpace** [comment]
This is a components library, for multi-page applications, different pages under each menu item, you need to use the parent library https://github.com/TangleSpace/hydralit
There are code examples explaining how you don't need to create the links and run the applications yourself, the library will handle all of it for you, please see the code examples for how this works at the link https://github.com/TangleSpace/hydralit
