### ISSUE TITLE
How to cancel the menu of the navbar login

### ISSUE THREAD

**Issue by SynchronyML** [TangleSpace/hydralit_components#15]
Hello, thank you very much for the development of hydralit_components, it helps me a lot.
I have a question and want to ask you, how can I turn off the option about logout in the navigation bar, my website does not need to log in and log out.
Thank you so much

**Comment by TangleSpace** [comment]
Thanks. You can turn off the logout option by leaving that option None, for example, if you create the navbar without specifying a value for the `login_name` variable, it will not appear on the navbar.

```
menu_data = [
    {'icon': "far fa-copy", 'label':"Left End"},
    {'id':'Copy','icon':"🐙",'label':"Copy"},
    {'icon': "fa-solid fa-radar",'label':"Dropdown1", 'submenu':[{'id':' subid11','icon': "fa fa-paperclip", 'label':"Sub-item 1"},{'id':'subid12','icon': "💀", 'label':"Sub-item 2"},{'id':'subid13','icon': "fa fa-database", 'label':"Sub-item 3"}]},
    {'icon': "far fa-chart-bar", 'label':"Chart"},#no tooltip message
    {'id':' Crazy return value 💀','icon': "💀", 'label':"Calendar"},
    {'icon': "fas fa-tachometer-alt", 'label':"Dashboard",'ttip':"I'm the Dashboard tooltip!"}, #can add a tooltip message
    {'icon': "far fa-copy", 'label':"Right End"},
    {'icon': "fa-solid fa-radar",'label':"Dropdown2", 'submenu':[{'label':"Sub-item 1", 'icon': "fa fa-meh"},{'label':"Sub-item 2"},{'icon':'🙉','label':"Sub-item 3",}]},
]

menu_id = hc.nav_bar(
    menu_definition=menu_data,
    home_name='Home',
)
```

**Comment by SynchronyML** [comment]
Thanks a lot for your help, it worked for me. 
I would also like to ask, can I bind the menu to the subdomain?
For example, my ip address is 127.0.0.1, I want the home page address to be 127.0.0.1, and the first option in the navigation bar ip address is 127.0.0.1/first_app？
