### ISSUE TITLE
Space above the navbar

### ISSUE THREAD

**Issue by ncavaglione** [TangleSpace/hydralit_components#17]
![image](https://user-images.githubusercontent.com/89771703/155947349-98df848c-c9e5-4709-a82c-5e5cfc4bb41f.png)
Streamlit==1.6.0
hydralit-components==1.0.9

You can reproduce the example with the navbar sample [code](https://github.com/TangleSpace/hydralit_components/blame/main/README.md#L192).
I was previously using Streamlit==0.89 and the navbar was sticked to the top so downgrading is an option (but limits the Streamlit features we can use). 

How can we remove this space ?

**Comment by junholv** [comment]
Hi,

you need to use sticky mode in your menu_id : 

menu_id = hc.nav_bar(
    menu_definition=menu_data,
    override_theme=over_theme,
    home_name='Accueil',
    login_name='Déconnexion',
    hide_streamlit_markers=True, #will show the st hamburger as well as the navbar now!
    sticky_nav=True, #at the top or not
    **sticky_mode='sticky',** #jumpy or not-jumpy, but sticky or pinned
)

**Comment by ncavaglione** [comment]
Hi, thanks for your reply. This partially solves it because does suppress the space but:
1) It is not a pinned but sticky navbar now
2) There is glitches where the space appears and disappears for one second when navigating to a different tab.

**Comment by TangleSpace** [comment]
Streamlit have messed with their component formatting, so the best the nav bar can do is allow room for the sidebar flip out bottom, making an even margin on the opposite side and a small gap at the top using the `hide_streamlit_markers=True`. Anything more, talk to Streamlit, as the $800M company doesn't need anymore of my free code to provide functionality they are looking to replace.
