### ISSUE TITLE
info_card content text size

### ISSUE THREAD

**Issue by john-mercer-allstripes** [TangleSpace/hydralit_components#18]
Hi @TangleSpace 
How do you change the font size of the content of a card?

e.g. here making 

![image](https://user-images.githubusercontent.com/94140924/159757661-b49d5467-c772-4c9c-98b4-0a2fb6e37e42.png)

making the 395,495 larger

**Comment by TimX914** [comment]
I have the same question...

**Comment by TangleSpace** [comment]
version 1.0.10 added 3 new parameters to the infocard component to adjust the title text size, the content text size and the icon size.

title_text_size
content_text_size
icon_size

can use any HTML valid sizing, for example "2.5rem", "80%","150px" etc.
