### ISSUE TITLE
make it possible to override label:null for fa-user-circle

### ISSUE THREAD

**Issue by fredzannarbor** [TangleSpace/hydralit_components#2]
Hi,

the use case that makes the most sense for me is to have everyone automatically logged in as guest/access level 1 and then sign in for access to premium or admin features at levels 2 and above.  But this means that a previously registered user has to figure out that they are logged in as a guest and then log out of the guest account and log in with their username/pw.    

This is a bit tricky to figure out just based on the user-circle icon and hovertip Guest:Login.  It looks as if the menu bar NavBar.tsx currently automatically appends the fa-user-circle with null label to the right hand end of every nav bar. So I would like to be able to configure  that label/icon so I can replace it with something like "Log In as Registered User" or "Return Signin".

I did this in my static javascript:

<img width="1558" alt="Screen Shot 2021-10-05 at 4 53 23 PM" src="https://user-images.githubusercontent.com/1165771/136103816-54e77e5c-5a9e-42eb-b053-aa57d8daad2c.png">
 but obviously I don't like to rely on writing over pip installed libraries.

I'm open to other ideas, this just seems like the most straightforward.

**Comment by fredzannarbor** [comment]
thanks!

**Comment by TangleSpace** [comment]
sorry Fred, it's still on my list, i needed to do a patch release for the sticky mode on the navbar since i was getting more and more tickets for it, i haven't forgotten about this, i meant to ask, would it be nicer if you could also select a couple of different styles for the navbar, not just the icons? like the more traditional looking menu for example, https://getbootstrap.com/docs/4.0/components/navbar/#color-schemes

**Comment by fredzannarbor** [comment]
.I'm happy with the color scheme I have now, because I try to avoid using
the conventional aqua/pastel/flat palettes, but options are good.  I like
having lots of control over fonts and icon images, too.

*Nimble Books LLC*
*The AI Lab for Book-Lovers <http://NimbleBooks.com>*
---

**Comment by TangleSpace** [comment]
I have pushed a new release with a fix for this issue, thank you very much for your support and hopefully you enjoy some of the other new features and fixes in this release.
