### ISSUE TITLE
vertical NavBar 

### ISSUE THREAD

**Issue by xueliang** [TangleSpace/hydralit_components#21]
Hello, is it possible to make the navbar vertically, on the left side the of the webpage? thanks.

**Comment by TangleSpace** [comment]
yes, just wrap the navbar component in a with statement for the side bar.

import streamlit as st
import hydralit_components as hc

menu_data = [
    {'id': 'page1', 'label': 'First Page'},
    {'id': 'page2', 'label': 'Second Page'}
]

with st.sidebar:
  item_id = hc.nav_bar(
      menu_definition=menu_data)

st.write(item_id)
