### ISSUE TITLE
Modal pop-up not working

### ISSUE THREAD

**Issue by Rafael-Silva-Oliveira** [TangleSpace/hydralit_components#25]
I was trying to deploy an app with the examples provided for the modal pop-up, but when I click the button, nothing shows up. 

In the hydralit-components repo it mentions this:

"NOTE: You need to force reload (browser refresh) the entire page after the experiemntal features have been enabled (you will see a notification in the terminal) to ensure the additions have been loaded into the web page."

How can I force reload the browser? And is this even the issue or the modal doesn't work on apps that have been deployed? Thanks!

Streamlit version 3.10.0
Python version 3.9.7
Latest version of hydralit as of this post

**Comment by jgomeher83** [comment]
Could you solve the issue?
