### ISSUE TITLE
space to the left of the navbar

### ISSUE THREAD

**Issue by Casyfill** [TangleSpace/hydralit_components#3]
Couple of issues when I tried the example

First, this f-rstring `f"{menu_id=}"` does not work on python 3.7 or less, so maybe it can be replaced with `f"menu_id={menu_id}"`.

More importantly, I've got this as a result:
![Screen Shot 2021-10-11 at 11 44 12 AM](https://user-images.githubusercontent.com/2675621/136819008-d20f32ed-ff81-4ded-bd2a-747ff6cad78b.png)

Not sure what is the reason but this empty space does not look good :-/

**Comment by TangleSpace** [comment]
> Thanks @TangleSpace.
> 
> 1. it's not a type nor fstrings themselves, https://tirkarthi.github.io/programming/2019/05/08/f-string-debugging.html. The syntaxis `{var=}` was introduced in python 3.8 as [described here](https://tirkarthi.github.io/programming/2019/05/08/f-string-debugging.html)
> 2. Thanks for the explanation. I assumed Github issues are here to raise awareness of the issues. If the maintainers/developers are aware of this (albeit I can't see this on the screenshots), that is good news.

1. _First, this f-rstring f"{menu_id=}" does not work on python 3.7 or less_, You can see (hopefully) it's neither correct 3.6+ syntax or 3.8 syntax, so as i said, without the typo it works just fine in 3.6 onwards.

2. You mean this screenshot at the top of the homepage within the gif, demonstrating the different appearance options of the navbar, that shows the gap on the left when in sticky mode. 
![image](https://user-images.githubusercontent.com/50782232/136850398-20289b64-4aad-4b18-8a45-62610c1eacf6.png)
The issues **are** here to raise awareness, you pointed out a typo (albeit not directly) thank you, and you asked a terse question as to why the gap is on the left, both of which I've answered. Feel free to raise any issues/questions/comments as you please.
