### ISSUE TITLE
NavBar return value on initial load is label instead of id

### ISSUE THREAD

**Issue by Daveography** [TangleSpace/hydralit_components#7]
**Issue:** When the NavBar is first rendered, the component returns the first item's `label` value even if `id` is provided.

**Reproduction:**
`sample.py`:
```python
import streamlit as st
import hydralit_components as hc

menu_data = [
    {'id': 'page1', 'label': 'First Page'},
    {'id': 'page2', 'label': 'Second Page'}
]

item_id = hc.nav_bar(
    menu_definition=menu_data,
)

st.write(item_id)
```

Exec:
```bash
streamlit run sample.py
```

**Expected behaviour:** `page1` is written to the app on first load.
**Actual behaviour:** `First Page` is written to the app on first load.
**Note:** The expected `id` value is written when clicking the menu items after the app has loaded.

**Suggested fix:**
Looks like it would be a quick fix to NavBar's `__init.py__` (starting at line 57) to return `id` if it exists, or else `label` as a fallback:
```python
    if component_value is None:
        if first_select > len(menu_definition):
            if login_name is not None:
                return login_name
            else:
                menu_item = menu_definition[-1]

        elif home_name is None:
            menu_item = menu_definition[first_select]

        else:
            if first_select == 0:
                return home_name
            else:
                menu_item = menu_definition[(first_select-1)]

        if 'id' in menu_item:
            return menu_item['id']
        else:
            return menu_item['label']
    else:
        return component_value
```

**Comment by TangleSpace** [comment]
new release that has implemented the fix you provided, top work, thank you very much!
