### ISSUE TITLE
Nav Bar jumps arround

### ISSUE THREAD

**Issue by ChrisChross** [TangleSpace/hydralit_components#8]
Hey @TangleSpace,

not sure if I am the only one who has that problem, 
but if I click on an item in the nabber the whole bar jumps around. 

https://user-images.githubusercontent.com/19912393/138742942-26716b8e-bde8-4727-8652-0723f6a95407.mov

Any ideas why that could happen or how to fix it? 

* [bug]

**Comment by TangleSpace** [comment]
Thanks, this is known issue related to the Streamlit status "Running" div that appears at the top of the page during execution. There is a fix coming in the next release that should resolve this jumping issue. if you're unhappy with it, you can disable the sticky property for now.

**Comment by TangleSpace** [comment]
sticky jumpiness has been addressed, please see the package repo readme for details, as the sticky behaviour has changed. Thanks very much for your feedback.
